#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 18 15:34:56 PET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Nostalgia_v5.1.zip
enableShaders=false
